export const algorithmList = [
  { algorithm: 'md4', type: 'hash' },
  { algorithm: 'md5', type: 'hash' },
  { algorithm: 'pbkdf2', type: 'hash' },
  { algorithm: 'ripemd128', type: 'hash' },
  { algorithm: 'ripemd160', type: 'hash' },
  { algorithm: 'ripemd256', type: 'hash' },
  { algorithm: 'ripemd320', type: 'hash' },
  { algorithm: 'sha1', type: 'hash' },
  { algorithm: 'sha3', type: 'hash' },
  { algorithm: 'sha224', type: 'hash' },
  { algorithm: 'sha256', type: 'hash' },
  { algorithm: 'sha384', type: 'hash' },
  { algorithm: 'sha512', type: 'hash' },
  { algorithm: 'md4', type: 'hmac-hash' },
  { algorithm: 'md5', type: 'hmac-hash' },
  { algorithm: 'pbkdf2', type: 'hmac-hash' },
  { algorithm: 'ripemd128', type: 'hmac-hash' },
  { algorithm: 'ripemd160', type: 'hmac-hash' },
  { algorithm: 'ripemd256', type: 'hmac-hash' },
  { algorithm: 'ripemd320', type: 'hmac-hash' },
  { algorithm: 'sha1', type: 'hmac-hash' },
  { algorithm: 'sha3', type: 'hmac-hash' },
  { algorithm: 'sha224', type: 'hmac-hash' },
  { algorithm: 'sha256', type: 'hmac-hash' },
  { algorithm: 'sha384', type: 'hmac-hash' },
  { algorithm: 'sha512', type: 'hmac-hash' },
  { algorithm: 'AES', type: 'block-cipher' },
  { algorithm: 'DES', type: 'block-cipher' },
  { algorithm: 'Triple DES', type: 'block-cipher' },
];
