export const algorithmList = [
  { algorithm: 'MD4', type: 'hash' },
  { algorithm: 'MD5', type: 'hash' },
  { algorithm: 'RIPEMD128', type: 'hash' },
  { algorithm: 'RIPEMD160', type: 'hash' },
  { algorithm: 'RIPEMD256', type: 'hash' },
  { algorithm: 'RIPEMD320', type: 'hash' },
  { algorithm: 'SHA1', type: 'hash' },
  { algorithm: 'SHA3', type: 'hash' },
  { algorithm: 'SHA224', type: 'hash' },
  { algorithm: 'SHA256', type: 'hash' },
  { algorithm: 'SHA384', type: 'hash' },
  { algorithm: 'SHA512', type: 'hash' },
  { algorithm: 'HmacMD4', type: 'hmac-hash' },
  { algorithm: 'HmacMD5', type: 'hmac-hash' },
  { algorithm: 'HmacRIPEMD128', type: 'hmac-hash' },
  { algorithm: 'HmacRIPEMD160', type: 'hmac-hash' },
  { algorithm: 'HmacRIPEMD256', type: 'hmac-hash' },
  { algorithm: 'HmacRIPEMD320', type: 'hmac-hash' },
  { algorithm: 'HmacSHA1', type: 'hmac-hash' },
  { algorithm: 'HmacSHA3', type: 'hmac-hash' },
  { algorithm: 'HmacSHA224', type: 'hmac-hash' },
  { algorithm: 'HmacSHA256', type: 'hmac-hash' },
  { algorithm: 'HmacSHA384', type: 'hmac-hash' },
  { algorithm: 'HmacSHA512', type: 'hmac-hash' },
  { algorithm: 'reverse', type: 'string' },
  { algorithm: 'join', type: 'string' }
];
